version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "25672:5672"   # AMQP
      - "35672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  server:
    build: ./server
    container_name: server
    volumes:
      - ./output:/app/output
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    ports:
      - "20000:20000"
    networks:
      - backend
    command: tail -f /dev/null  # <--- ничего не запускает, просто "висит"

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: constructioncompany
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "25432:5432"  # Проброс порта
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d  # Монтируем локальную папку с инициализационными скриптами
    networks:
      - backend

networks:
  backend:
    driver: bridge